# Generated by Django 4.2.1 on 2023-05-08 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="register",
            old_name="eddit_at",
            new_name="edit_at",
        ),
    ]
